name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to github container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the container
      run: |
        docker build . --file Dockerfile --tag ghcr.io/mrguyperson/dev_toolbox:latest
        docker run ghcr.io/mrguyperson/dev_toolbox:latest
        docker push ghcr.io/mrguyperson/dev_toolbox:latest
